In [1]:
import numpy as np
import matplotlib.pyplot as plt
import glob,sys,os
from xml_module import waves_from_xml_file_SNUB
from xml_module_HY_features import measurements_from_xml, descriptions_xml
import pandas as pd

# for extract features
import xml.etree.ElementTree as et


In [2]:
path = './ECG Sample 4 Hospitals/4. HY/f6f51700-b41c-11ee-4823-00c68da90029.xml'
xml_ns = {'hy':'http://www3.medical.philips.com'}
root = et.parse(path)
descriptions_xml(root)

['SINUS RHYTHM normal P axis, V-rate  50- 99',
 'MULTIPLE VENTRICULAR PREMATURE COMPLEXES V complexes w/ short R-R intervls',
 'RBBB AND LAFB QRSd >120mS, axis(-40,240)',
 'BASELINE WANDER IN LEAD(S) V1,V2,V5,V6',
 '- ABNORMAL ECG -',
 '*',
 '*',
 '*',
 '*']

In [3]:
measurements_from_xml(root)


['56', '190', '144', '468', '452', '0', '-11', '18']

In [4]:
wave=waves_from_xml_file_SNUB(path)
wave

[array([-120., -120., -120., ...,    0.,    0.,    0.]),
 array([-458., -461., -465., ...,    0.,    0.,    0.]),
 array([-338., -341., -345., ...,    0.,    0.,    0.]),
 array([289. , 290.5, 292.5, ...,  -0. ,  -0. ,  -0. ]),
 array([109. , 110.5, 112.5, ...,   0. ,   0. ,   0. ]),
 array([-398., -401., -405., ...,    0.,    0.,    0.]),
 array([954., 954., 955., ...,   0.,   0.,   0.]),
 array([-294., -290., -287., ...,    0.,    0.,    0.]),
 array([182., 182., 182., ...,   0.,   0.,   0.]),
 array([951., 951., 951., ...,   0.,   0.,   0.]),
 array([699., 700., 701., ...,   0.,   0.,   0.]),
 array([454., 455., 456., ...,   0.,   0.,   0.])]