In [1]:
import numpy as np
import matplotlib.pyplot as plt
from xml_module_muse import waves_from_xml_file, measurements_from_xml_file

import pandas as pd

# for extract features
import xml.etree.ElementTree as et


In [2]:
path = './ECG Sample 4 Hospitals/1. ISH/ECG/2024020809131591.xml'
# path = './ECG Sample 4 Hospitals/2. BSCH/72696/202401151045356632_wfmkbyqibqd.xml'

In [3]:
waves_from_xml_file(path)

[array([-0.02928, -0.02928, -0.02928, ...,  0.08784,  0.08784,  0.08784]),
 array([-0.06832, -0.06832, -0.06832, ...,  0.13664,  0.13664,  0.13664]),
 array([-0.03904, -0.03904, -0.03904, ...,  0.0488 ,  0.0488 ,  0.0488 ]),
 array([ 0.0488 ,  0.0488 ,  0.0488 , ..., -0.11224, -0.11224, -0.11224]),
 array([0.00488, 0.00488, 0.00488, ..., 0.01952, 0.01952, 0.01952]),
 array([-0.05368, -0.05368, -0.05368, ...,  0.09272,  0.09272,  0.09272]),
 array([-0.05856, -0.05856, -0.05856, ...,  0.23424,  0.23424,  0.23424]),
 array([-0.0976 , -0.0976 , -0.0976 , ..., -0.20496, -0.20496, -0.20496]),
 array([-0.0488 , -0.0488 , -0.0488 , ...,  0.02928,  0.02928,  0.02928]),
 array([-0.03904, -0.03904, -0.03904, ..., -0.00976, -0.00976, -0.00976]),
 array([-0.07808, -0.07808, -0.07808, ...,  0.06832,  0.06832,  0.06832]),
 array([-0.06832, -0.06832, -0.06832, ...,  0.03904,  0.03904,  0.03904])]

In [4]:
measurements_from_xml_file(path)

['68', '166', '108', '424', '450', '2', '71', '43']